### ISSUE TITLE
problem with PID file

### ISSUE THREAD

**Issue by mcdemon05** [accel-ppp/accel-ppp#120]
I rent new server with Debian 11

```
apt update && apt upgrade
apt-get install -y build-essential cmake gcc linux-headers-`uname -r` git libpcre3-dev libssl-dev
git clone https://github.com/accel-ppp/accel-ppp.git /opt/accel-ppp-code
mkdir /opt/accel-ppp-code/build
cd /opt/accel-ppp-code/build/
cmake -DCMAKE_INSTALL_PREFIX=/usr -DKDIR=/usr/src/kernels/`uname -r` -DCPACK_TYPE=Debian11 ..
make
cpack -G DEB
dpkg -i accel-ppp.deb
systemctl enable accel-ppp
```

How I can fix this error?

> service accel-ppp status
> ● accel-ppp.service - Accel-PPP
>      Loaded: loaded (/lib/systemd/system/accel-ppp.service; enabled; vendor preset: enabled)
>      Active: active (running) since Thu 2024-01-11 08:40:04 UTC; 3s ago
>     Process: 400 ExecStart=/usr/sbin/accel-pppd -d -p /var/run/accel-pppd.pid -c /etc/accel-ppp.conf (code=exited, status=0/SUCCESS)
>    Main PID: 409 (accel-pppd)
>       Tasks: 6 (limit: 508)
>      Memory: 4.2M
>         CPU: 13ms
>      CGroup: /system.slice/accel-ppp.service
>              └─409 /usr/sbin/accel-pppd -d -p /var/run/accel-pppd.pid -c /etc/accel-ppp.conf
> 
> Jan 11 08:40:04 khb systemd[1]: Starting Accel-PPP...
> **Jan 11 08:40:04 khb systemd[1]: accel-ppp.service: Can't open PID file /run/accel-pppd.pid (yet?) after start: Operation not permitted**
> Jan 11 08:40:04 khb systemd[1]: Started Accel-PPP.

**Comment by DmitriyEshenko** [comment]
Hi, it looks like systend unit warning issue, but daemon works as I see.
