### ISSUE TITLE
bug: pptp doesnt work without connlimit on Alpine Linux

### ISSUE THREAD

**Issue by nuclearcat** [accel-ppp/accel-ppp#131]
If config dont have connlimit enabled, and enabled BEFORE pptp in modules, it will generate following error:
```
[2024-04-09 22:30:09.911]loader: failed to load 'pptp': Error relocating /usr/local/lib64/accel-ppp/libpptp.so: connlimit_check: symbol not found
```

**Comment by kugel-** [comment]
This patch helps. Need a PR for it?

```
diff --git a/accel-pppd/ctrl/pppoe/CMakeLists.txt b/accel-pppd/ctrl/pppoe/CMakeLists.txt
index 808cd51..fd4f9a3 100644
--- a/accel-pppd/ctrl/pppoe/CMakeLists.txt
+++ b/accel-pppd/ctrl/pppoe/CMakeLists.txt
@@ -13,7 +13,7 @@ SET(sources ${sources} tr101.c)
 ENDIF(RADIUS)

 ADD_LIBRARY(pppoe SHARED ${sources})
-TARGET_LINK_LIBRARIES(pppoe vlan-mon)
+TARGET_LINK_LIBRARIES(pppoe vlan-mon connlimit)
 set_property(TARGET pppoe PROPERTY CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
 set_property(TARGET pppoe PROPERTY INSTALL_RPATH ${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}/accel-ppp)

```

**Comment by svlobanov** [comment]
@kugel-  please send this as a PR

**Comment by nuclearcat** [comment]
Thanks @kugel- , merged your patch.

**Comment by Tokarak** [comment]
Thank you. I just hit a related bug in the "pppoe" module on Entware (1.12.0). 
`[2024-08-21 18:30:23.973]loader: failed to load 'pppoe': /opt/lib/accel-ppp/libpppoe.so: undefined symbol: rad_packet_add_int` 
I'm not loading the radius module because I'm using chap-secrets.
I suppose I just have to link radius too?

**Comment by svlobanov** [comment]
@Tokarak just place radius module before pppoe, I will send a patch regarding this issue. The same issue in alpine linux

**Comment by Tokarak** [comment]
Correct, it doesn't build with `-DRADIUS=FALSE`, tested on Rocky Linux. Closing and moving the discussion back to the linked issue. 
Probably a good thing, it's better to fix the underlying dependency on radius.
