### ISSUE TITLE
libpcre(libpcre3) was removed from Debian13

### ISSUE THREAD

**Issue by svlobanov** [accel-ppp/accel-ppp#173]
libpcre(libpcre3) was removed from Debian13 (https://packages.debian.org/search?keywords=libpcre3 ) so it's not possible to build accel-ppp anymore on Debian 13+
The replacement is libpcre2 (https://packages.debian.org/trixie/libpcre2-8-0) that is available in all actual Debian distros

It is removed from Debian because libpcre upstream is not supported anymore

Fedora rawhide (2024-08-17) still provides libpcre (pcre-devel 8.45 1.fc41.7), but they are also migrating everything to pcre2: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/K3BUC6T5VIG7LXOV4RVFO7IUPE2LGA2J/

Good example what do we need to do to migrate to pcre2: https://github.com/bazsi/syslog-ng/commit/cb6de08dc9078644d48ca536b5660e406b1a50d6

My proposal is to migrate to libpcre2 (change accel-ppp source code and build/ci system) and stop supporting libpcre(libpcre3)

P.S. RHEL8+ provides libpcre2 (pcre2-devel) so this migration is safe for actual Linux distros.

**Comment by svlobanov** [comment]
@DmitriyEshenko  @nuclearcat looks like function cli_register_regexp_cmd is never used (https://github.com/accel-ppp/accel-ppp/blob/0eb54934a8746091a5f3eef2ae0db726975c24da/accel-pppd/cli/cli.c#L66 ) so we can't test it after migrating from pcre to pcre2. let's remove it from source code

**Comment by svlobanov** [comment]
openwrt also dropped libpcre support: https://github.com/openwrt/packages/pull/24035

**Comment by Neustradamus** [comment]
Have you progressed on it?

**Comment by andamasov** [comment]
@svlobanov, assuming this is solved and we can close the issue?

**Comment by Neustradamus** [comment]
About Debian, you can see binaries on Debian Tracker at bottom left:
- https://tracker.debian.org/pkg/pcre2

**Comment by svlobanov** [comment]
fixed in https://github.com/accel-ppp/accel-ppp/pull/185
