### ISSUE TITLE
many abnormal finish state sessions

### ISSUE THREAD

**Issue by tictak** [accel-ppp/accel-ppp#27]
![image](https://user-images.githubusercontent.com/2810016/141324984-a64674d7-2250-4c18-8251-0ea4a95e8f36.png)

abnormal finish state sessions sames share common  rx-bytes,tx-bytes

**Comment by DmitriyEshenko** [comment]
Hello @tictak did you check the reason in the logs? You can set `verbose=1` to each section except `[modules]` and carefully looks through logs. Also, some fixes for clear counters were added. https://github.com/accel-ppp/accel-ppp/commit/b8ab27c2254e1668a175a3ae9ad038e5db7d6851

Which accel-ppp version is running?

**Comment by DmitriyEshenko** [comment]
Closed. Reason: Author did not respond for a long time.
