### ISSUE TITLE
ipoe: calling-sid=username with start=auto 

### ISSUE THREAD

**Issue by wkg** [accel-ppp/accel-ppp#37]
see subject, Is that how it should be? 
calling-sid=mac in config, but on the radius not mac: "Calling-Station-Id = 'qinq.200.3005'"

**Comment by DmitriyEshenko** [comment]
Hi @wkg , looks like we need to mention this in docs, it should work for mode=L2 and start=dhcpv4 or UP

**Comment by wkg** [comment]
> Hi @wkg , looks like we need to mention this in docs, it should work for mode=L2 and start=dhcpv4 or UP

Can't make a mac for "start"? with "dhcpv4" or "up" impossible make ipv6-only session....

**Comment by DmitriyEshenko** [comment]
Correct, PPP (PPTP, l2TP, SSTP, PPPoE) can be ipv6 only, but unfortunately, ipv6-only does not implement for IPoE. IPoE is still dual-stack and require ipv4

As for mac in `Calling-Station-Id` I think it is possible to implement https://github.com/accel-ppp/accel-ppp/blob/master/accel-pppd/ctrl/ipoe/ipoe.c#L2171

Try to create a feature request https://phabricator.accel-ppp.org

**Comment by wkg** [comment]
Ok, thank you
