### ISSUE TITLE
Move xebd/accel-ppp into "accel-ppp" organization

### ISSUE THREAD

**Issue by Neustradamus** [accel-ppp/accel-ppp#38]
Dear @accel-ppp team, @xebd, @themiron, @DmitriyEshenko, @andamasov,

In first, I wish you a Happy New Year 2022!

Currently there is a problem, an historical problem!

It will be better to:
- Temporary transfer in other place : https://github.com/accel-ppp/accel-ppp
- Tranfer https://github.com/xebd/accel-ppp to https://github.com/accel-ppp/accel-ppp
- Update the upstream

Doc :
- https://help.github.com/en/articles/transferring-a-repository

Do you want help?

I have already done with success!

Thanks in advance.

Regards,

Neustradamus

Linked to:
- https://github.com/xebd/accel-ppp/issues/145

**Comment by Neustradamus** [comment]
Dear @accel-ppp team, @xebd, @themiron, @nuclearcat, @DmitriyEshenko, @andamasov, @sever-sever, 

It has not really done :/

Why have you not done it correctly?

Now, can you:
- Rename the https://github.com/xebd/accel-ppp to accel-ppp-temp
- Transfer the https://github.com/xebd/accel-ppp-temp to https://github.com/accel-ppp organization
- Transfer all issues (at this time here: https://github.com/xebd/accel-ppp/issues) into https://github.com/accel-ppp/accel-ppp

Inform all people who watch, has done a fork and a star to go at "good" repo from "bad" repo to new place.

Inform people who has done PR on "bad" place to do on "good" place...

Thanks in advance.

Linked to:
- https://github.com/xebd/accel-ppp/issues/145

**Comment by Neustradamus** [comment]
Note:

It is always possible to:
- Rename this current https://github.com/accel-ppp/accel-ppp to https://github.com/accel-ppp/accel-ppp-temp
- Transfer https://github.com/xebd/accel-ppp to accel-ppp organization and push all recent commits.

And all redirections will be here from https://github.com/xebd/accel-ppp to https://github.com/accel-ppp/accel-ppp

And inform people, it will be better for history, watchs, forks, stars, ...

**Comment by DmitriyEshenko** [comment]
Hi @Neustradamus , recently we make decisions that fork original repository and include @xebd as owner on organization repository. From time to time @xebd will syncing both. When all will clear for as in different places, we will migrate

**Comment by Neustradamus** [comment]
@DmitriyEshenko: Thanks for your answer!

Important:
The best solution is to do the renaming of https://github.com/accel-ppp/accel-ppp to accel-ppp-temp and to transfer https://github.com/xebd/accel-ppp into the organization (it must done by @xebd).
Redirection from xebd will be here, no lost.
Move issues from temp to good one after.
Inform people from old accel-ppp-temp to go good one.
Inform people who has done PRs...

Note: My initial request has been done 3yo soon, badly, this problem has not been solved yet.

**Comment by Neustradamus** [comment]
@DmitriyEshenko: Thanks for your answer!

Important:
The best solution is to do the renaming of https://github.com/accel-ppp/accel-ppp to accel-ppp-temp and to transfer https://github.com/xebd/accel-ppp into the organization (it must done by @xebd).
Redirection from xebd will be here, no lost.
Move issues from temp to good one after.
Inform people from old accel-ppp-temp to go good one.
Inform people who has done PRs...

Note: My initial request has been done 2020-07-30 (more 4yo), badly, this problem has not been solved yet.
- https://github.com/xebd/accel-ppp/issues/145

**Comment by Neustradamus** [comment]
@DmitriyEshenko: Have you progressed?

**Comment by DmitriyEshenko** [comment]
No. It is not  not in our plans for next 2 years.

**Comment by Neustradamus** [comment]
@DmitriyEshenko: It is very problematic!

**Comment by marekm72** [comment]
@Neustradamus: please be patient, while it would be interesting to know more about the project history and why there are the two repos (it's a bit of a mystery to me too), there are many more problematic things in the world.  I see you're reporting lots of issues in many projects, and I don't think it's a good idea to put such pressure on people.  On the other hand, if you can help fixing some real bugs, I think that would be welcome.  (Disclaimer: I'm just another user, not speaking for the project in any official way.)

**Comment by Neustradamus** [comment]
Dear all, we are in 2026, what is the situation about accel-ppp?
- https://github.com/xebd/accel-ppp VS https://github.com/accel-ppp/accel-ppp
- http://accel-ppp.org/ VS https://accel-ppp.io/
