### ISSUE TITLE
Vlan_mon Kernel 6.1.x  error talking to kernel

### ISSUE THREAD

**Issue by micron10** [accel-ppp/accel-ppp#70]
With kernel 6.1.x get changes in netlink and this error receive when run accel

[2022-12-15 20:25:37.740] libnetlink: RTNETLINK answers: Invalid argument
[2022-12-15 20:25:37.740] vlan_mon: nl_add_vlan_mon: error talking to kernel

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/include/net/netlink.h?id=9521c9d6a53df9c44a5f5ddbc229ceaf3cf79ef6 

This is part of changes in netlink

**Comment by svlobanov** [comment]
Does it work for older kernels?

**Comment by micron10** [comment]
with latest kernel 6.0.13 is fine.
changes in latrst 6.1 release

**Comment by micron10** [comment]
May be this changes in kernel 6.1 make problem : 

https://github.com/torvalds/linux/commit/690252f19f0e486abb8590b3a7a03d4e065d93d4

add 2 more  element in struct: 

const struct nlattr *miss_nest;
u16 miss_type;

--------
struct netlink_ext_ack {
        const char *_msg;
        const struct nlattr *bad_attr;
        const struct nla_policy *policy;
        const struct nlattr *miss_nest;
        u16 miss_type;
        u8 cookie[NETLINK_MAX_COOKIE_LEN];
        u8 cookie_len;
};

**Comment by micron10** [comment]
Here is changes for kernel 6.1 

https://github.com/torvalds/linux/commits/master/include/net/netlink.h

**Comment by micron10** [comment]
ok find where is a problem ,
i will post patch
